name: Test

on:
  pull_request:
    branches: [ develop ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
  
    steps:
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v1
      env:
        TEST: ${{ secrets.TEST }}
